volumes:
  data:

services:
  postgres:
    container_name: postgresKV
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234qwer
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "8000:8000"
    volumes:
      - data:/var/lib/postgresql
    networks:
      - kvsNetwork
  kvs:
    restart: always
    container_name: KVStore
    image: kvs:pg
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - postgres
    networks:
      - kvsNetwork

networks:
  kvsNetwork:
    driver: bridge
