volumes:
  data:

services:
  postgres:
    container_name: postgresKV
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234qwer
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  kvs:
    restart: always
    container_name: KVStore
    image: kvs:pg
    build:
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres


  proxy:
    image: nginx:latest
    container_name: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "8080"
    depends_on:
      - kvs


