volumes:
  data:

services:
#  postgres:
#    container_name: postgresKV
#    image: postgres:latest
#    environment:
#      - POSTGRES_PASSWORD=1234qwer
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#    volumes:
#      - data:/var/lib/postgresql
#
#

  kvs:
    restart: always
    container_name: KVStore
    image: kvs:pg
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    depends_on:
#      postgres:
#        condition: service_started



