volumes:
  data:

services:
  postgres:
    container_name: postgresKV
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - data:/var/lib/postgresql

  kvs:
    restart: always
    container_name: KVStore
    image: kvs:pg
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started



